import {
  useQuery,
  useMutation,
  useQueryClient
} from '@tanstack/react-query';

import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  query,
  orderBy,
  where
} from 'firebase/firestore';

import { db } from '../lib/firebase';
import { useAuth } from './useAuth';
import { deleteUploadedFile } from '../utils/uploadFile';

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */
function removeUndefined<T>(value: T): T {
  if (Array.isArray(value)) {
    return value
      .filter((item) => item !== undefined)
      .map((item) => removeUndefined(item)) as T;
  }

  if (
    value !== null &&
    typeof value === 'object'
  ) {
    const cleaned: Record<string, unknown> = {};

    for (const [key, val] of Object.entries(value)) {
      if (val !== undefined) {
        cleaned[key] = removeUndefined(val);
      }
    }

    return cleaned as T;
  }

  return value;
}

export type QuoteStatus =
  | 'Pending'
  | 'Quoted'
  | 'Accepted'
  | 'Rejected'
  | 'Completed';

export type QuoteRequestType =
  | '3d-model'
  | 'image'
  | 'idea';

export type QuoteDimensions = {
  length?: number;
  width?: number;
  height?: number;
  unit?: 'mm' | 'cm' | 'in';
};

export type Quote = {
  id: string;
  date: string;

  /* Customer */
  customerId?: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;

  /* Request */
  requestType: QuoteRequestType;

  /* Product / customization */
  productId?: string;
  productName?: string;
  variantLabel?: string;

  /* Uploaded file */
  fileName?: string;
  fileUrl?: string;

  /* Printing specifications */
  material?: string;
  color?: string;
  infill?: number;
  layerHeight?: number;
  quantity: number;

  /* Model calculation */
  volume?: number;
  estimatedWeight?: number;
  estimatedPrice?: number;

  /* Image / idea requests */
  dimensions?: QuoteDimensions;
  description?: string;

  /* Customer notes */
  notes?: string;

  /* Quote lifecycle */
  status: QuoteStatus;

  /* Admin pricing */
  adminPrice?: number;
  adminNotes?: string;
};

/*
 * Data required when creating a quote.
 *
 * id, date and status are generated by the hook.
 */
export type CreateQuoteData = Omit<
  Quote,
  'id' | 'date' | 'status'
>;

/* -------------------------------------------------------------------------- */
/* Admin: Get all quotes                                                      */
/* -------------------------------------------------------------------------- */

export function useQuotes() {
  return useQuery({
    queryKey: ['quotes'],

    queryFn: async (): Promise<Quote[]> => {
      const quotesQuery = query(
        collection(db, 'quotes'),
        orderBy('date', 'desc')
      );

      const snapshot =
        await getDocs(quotesQuery);

      return snapshot.docs.map(
        (quoteDoc) => ({
          id: quoteDoc.id,
          ...quoteDoc.data()
        })
      ) as Quote[];
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Customer: Get current user's quotes                                        */
/* -------------------------------------------------------------------------- */

export function useMyQuotes() {
  const { user } = useAuth();

return useQuery({
  queryKey: ['my-quotes', user?.uid],

  queryFn: async () => {
    if (!user) return [];

    const q = query(
      collection(db, 'quotes'),
      where('customerId', '==', user.uid)
    );

    const snapshot = await getDocs(q);

    const quotes = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data()
    })) as Quote[];

    return quotes.sort(
      (a, b) =>
        new Date(b.date).getTime() -
        new Date(a.date).getTime()
    );
  },

  enabled: !!user,

  staleTime: 5 * 60 * 1000,
  refetchOnWindowFocus: false,
  refetchOnMount: false,
});
}

/* -------------------------------------------------------------------------- */
/* Submit new quote                                                           */
/* -------------------------------------------------------------------------- */

export function useSubmitQuote() {
  const queryClient =
    useQueryClient();

  const { user } = useAuth();

  return useMutation({
    mutationFn: async (
      quoteData: CreateQuoteData
    ) => {
      /*
       * A quote must always belong to
       * an authenticated customer.
       */
      if (!user) {
        throw new Error(
          'You must be logged in to submit a quote.'
        );
      }

      const newQuote: Omit<
  Quote,
  'id'
> = {
  ...quoteData,

  customerId: user.uid,

  date: new Date().toISOString(),

  status: 'Pending'
};

const cleanedQuote =
  removeUndefined(newQuote);

const quoteRef =
  await addDoc(
    collection(db, 'quotes'),
    cleanedQuote
  );

      return quoteRef;
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Update quote - Admin                                                       */
/* -------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------- */
/* Customer: Accept / Reject quote                                            */
/* -------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------- */
/* Update quote - Admin                                                       */
/* -------------------------------------------------------------------------- */

export function useUpdateQuote() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<Quote> & {
      id: string;
    }) => {
      await updateDoc(
        doc(db, 'quotes', id),
        data
      );
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Delete quote                                                               */
/* -------------------------------------------------------------------------- */

export function useDeleteQuote() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      fileUrl
    }: {
      id: string;
      fileUrl?: string;
    }) => {
      /*
       * Remove uploaded file first,
       * if this quote has one.
       */
      if (fileUrl) {
        await deleteUploadedFile(
          fileUrl
        );
      }

      /*
       * Then remove the Firestore
       * quote document.
       */
      await deleteDoc(
        doc(db, 'quotes', id)
      );
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}/* -------------------------------------------------------------------------- */
/* Customer: Accept / Reject quote                                             */
/* -------------------------------------------------------------------------- */

export function useRespondToQuote() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      status,
    }: {
      id: string;
      status: 'Accepted' | 'Rejected';
    }) => {
      if (!id) {
        throw new Error('Quote ID is required.');
      }

      await updateDoc(
        doc(db, 'quotes', id),
        {
          status,
        }
      );
    },

    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: ['my-quotes'],
      });

      queryClient.invalidateQueries({
        queryKey: ['quotes'],
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quote', variables.id],
      });
    },
  });
}


