import {
  useQuery,
  useMutation,
  useQueryClient
} from '@tanstack/react-query';

import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  query,
  orderBy,
  where
} from 'firebase/firestore';

import { db } from '../lib/firebase';
import { useAuth } from './useAuth';
import { deleteUploadedFile } from '../utils/uploadFile';

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */

export type QuoteStatus =
  | 'Pending'
  | 'Quoted'
  | 'Accepted'
  | 'Rejected'
  | 'Completed';

export type QuoteRequestType =
  | '3d-model'
  | 'image'
  | 'idea';

export type QuoteDimensions = {
  length?: number;
  width?: number;
  height?: number;
  unit?: 'mm' | 'cm' | 'in';
};

export type Quote = {
  id: string;
  date: string;

  /* Customer */
  customerId?: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;

  /* Request */
  requestType: QuoteRequestType;

  /* Product / customization */
  productId?: string;
  productName?: string;
  variantLabel?: string;

  /* Uploaded file */
  fileName?: string;
  fileUrl?: string;

  /* Printing specifications */
  material?: string;
  color?: string;
  infill?: number;
  layerHeight?: number;
  quantity: number;

  /* Model calculation */
  volume?: number;
  estimatedWeight?: number;
  estimatedPrice?: number;

  /* Image / idea requests */
  dimensions?: QuoteDimensions;
  description?: string;

  /* Customer notes */
  notes?: string;

  /* Quote lifecycle */
  status: QuoteStatus;

  /* Admin pricing */
  adminPrice?: number;
  adminNotes?: string;
};

/*
 * Data required when creating a quote.
 *
 * id, date and status are generated by the hook.
 */
export type CreateQuoteData = Omit<
  Quote,
  'id' | 'date' | 'status'
>;

/* -------------------------------------------------------------------------- */
/* Admin: Get all quotes                                                      */
/* -------------------------------------------------------------------------- */

export function useQuotes() {
  return useQuery({
    queryKey: ['quotes'],

    queryFn: async (): Promise<Quote[]> => {
      const quotesQuery = query(
        collection(db, 'quotes'),
        orderBy('date', 'desc')
      );

      const snapshot =
        await getDocs(quotesQuery);

      return snapshot.docs.map(
        (quoteDoc) => ({
          id: quoteDoc.id,
          ...quoteDoc.data()
        })
      ) as Quote[];
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Customer: Get current user's quotes                                        */
/* -------------------------------------------------------------------------- */

export function useMyQuotes() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['my-quotes', user?.uid],

    queryFn: async (): Promise<Quote[]> => {
      if (!user) {
        return [];
      }

      const quotesQuery = query(
        collection(db, 'quotes'),
        where(
          'customerId',
          '==',
          user.uid
        ),
        orderBy('date', 'desc')
      );

      const snapshot =
        await getDocs(quotesQuery);

      return snapshot.docs.map(
        (quoteDoc) => ({
          id: quoteDoc.id,
          ...quoteDoc.data()
        })
      ) as Quote[];
    },

    enabled: !!user
  });
}

/* -------------------------------------------------------------------------- */
/* Submit new quote                                                           */
/* -------------------------------------------------------------------------- */

export function useSubmitQuote() {
  const queryClient =
    useQueryClient();

  const { user } = useAuth();

  return useMutation({
    mutationFn: async (
      quoteData: CreateQuoteData
    ) => {
      /*
       * A quote must always belong to
       * an authenticated customer.
       */
      if (!user) {
        throw new Error(
          'You must be logged in to submit a quote.'
        );
      }

      const newQuote: Omit<
        Quote,
        'id'
      > = {
        ...quoteData,

        customerId: user.uid,

        date: new Date().toISOString(),

        status: 'Pending'
      };

      const quoteRef =
        await addDoc(
          collection(db, 'quotes'),
          newQuote
        );

      return {
        id: quoteRef.id,
        ...newQuote
      };
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Update quote - Admin                                                       */
/* -------------------------------------------------------------------------- */

export function useUpdateQuote() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<Quote> & {
      id: string;
    }) => {
      await updateDoc(
        doc(db, 'quotes', id),
        data
      );
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}

/* -------------------------------------------------------------------------- */
/* Delete quote                                                               */
/* -------------------------------------------------------------------------- */

export function useDeleteQuote() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      fileUrl
    }: {
      id: string;
      fileUrl?: string;
    }) => {
      /*
       * Remove uploaded file first,
       * if this quote has one.
       */
      if (fileUrl) {
        await deleteUploadedFile(
          fileUrl
        );
      }

      /*
       * Then remove the Firestore
       * quote document.
       */
      await deleteDoc(
        doc(db, 'quotes', id)
      );
    },

    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['quotes']
      });

      queryClient.invalidateQueries({
        queryKey: ['my-quotes']
      });
    }
  });
}